#!/bin/bash

while getopts ":i:l:" opt; do
        case $opt in
        i)
		ID="$OPTARG"
		;;
        l)
		LOG="$OPTARG"
		;;
	\?)
		echo "Unknown Option: -$OPTARG" >&2
		exit 1
		;;
	:)
		echo "Option -$OPTARG requires an argument" >&2
		exit 1;
		;;
	esac
done

if [ "_${ID}_" == "__" ]; then
	echo '"-i $(ID)" not specified' >&2
	exit 1;
fi

if [ "_${LOG}_" == "__" ]; then
	LOG=./adfice-export.log
fi

echo "" >> $LOG
echo "----" >> $LOG
date --utc +%Y.%m.%d_%H.%M.%S%z >> $LOG
echo "ID: $ID" >> $LOG
node ./export-to-portal.js $ID >> $LOG
echo "----" >> $LOG
